## Variables
ARG CI_REGISTRY_IMAGE
ARG CI_PROJECT_ENV
ARG CI_VERSION_ENV

## Only stage to precompile
FROM ${CI_REGISTRY_IMAGE}/${CI_PROJECT_ENV}:${CI_VERSION_ENV}

MAINTAINER DevOps Team "bd-sistemas.cercomp@ufg.br"

COPY . /opt/weby
WORKDIR /opt/weby

ARG RAILS_ENV
ARG SECRET_KEY_BASE
ARG STORAGE_BUCKET
ARG STORAGE_ACCESS_KEY
ARG STORAGE_ACCESS_SECRET
ARG STORAGE_HOST

ENV RAILS_ENV $RAILS_ENV
ENV SECRET_KEY_BASE $SECRET_KEY_BASE
ENV STORAGE_BUCKET $STORAGE_BUCKET
ENV STORAGE_ACCESS_KEY $STORAGE_ACCESS_KEY
ENV STORAGE_ACCESS_SECRET $STORAGE_ACCESS_SECRET
ENV STORAGE_HOST $STORAGE_HOST

# Move file to not acess db
RUN mv config/initializers/email.rb config/
# Assets precompile
RUN bundle exec rake assets:precompile --trace
RUN bundle exec rake assets:clean
# Cleanup
RUN cp public/assets/.sprockets-manifest-*.json .
RUN bundle exec rake assets:clobber
RUN mkdir public/assets
RUN cp .sprockets-manifest-*.json public/assets/
# Init before system up
RUN mv config/email.rb config/initializers/

# Env to system
ENV PATH=/opt/weby/bin:/opt/weby/vendor/bundle/ruby/2.7.0/bin:$PATH

EXPOSE 3000:3000

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]
