## Variables
ARG CI_REGISTRY_IMAGE
ARG CI_PROJECT_ENV
ARG CI_VERSION_ENV

## Only stage to precompile
FROM ${CI_REGISTRY_IMAGE}/${CI_PROJECT_ENV}:${CI_VERSION_ENV} as base

MAINTAINER DevOps Team "bd-sistemas.cercomp@ufg.br"

# Copy files from first stage
COPY ./public/assets /opt/weby/public/assets

EXPOSE 3000:3000

CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]
